"""chamados_lembretes_confirmacao

Revision ID: 11dcbff52838
Revises: 4b3ffb87c806
Create Date: 2026-08-03 14:21:45.428720

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11dcbff52838"
down_revision: str | Sequence[str] | None = "4b3ffb87c806"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chamados", sa.Column("lembrete_confirmacao_1_enviado", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "chamados", sa.Column("lembrete_confirmacao_2_enviado", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chamados", "lembrete_confirmacao_2_enviado")
    op.drop_column("chamados", "lembrete_confirmacao_1_enviado")
    # ### end Alembic commands ###
