"""chamados_participantes_status

Revision ID: 4b3ffb87c806
Revises: 74f0527a9dd6
Create Date: 2026-08-03 13:31:02.108165

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b3ffb87c806"
down_revision: str | Sequence[str] | None = "74f0527a9dd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chamados_participantes", sa.Column("status", sa.Text(), nullable=False))
    op.add_column(
        "chamados_participantes",
        sa.Column("concluido_em", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chamados_participantes", "concluido_em")
    op.drop_column("chamados_participantes", "status")
    # ### end Alembic commands ###
