"""chamados_alerta_prazo_reaberturas

Revision ID: 542481d03082
Revises: 11dcbff52838
Create Date: 2026-08-03 14:26:26.081550

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "542481d03082"
down_revision: str | Sequence[str] | None = "11dcbff52838"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chamados",
        sa.Column("alerta_prazo_24h_enviado_em", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "chamados", sa.Column("reaberturas_solicitante_count", sa.SmallInteger(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chamados", "reaberturas_solicitante_count")
    op.drop_column("chamados", "alerta_prazo_24h_enviado_em")
    # ### end Alembic commands ###
