"""usuarios

Revision ID: 552599f9b52c
Revises: 9ef3ef37804a
Create Date: 2026-08-03 12:03:07.765321

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "552599f9b52c"
down_revision: str | Sequence[str] | None = "9ef3ef37804a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("email_lookup_hash", sa.Text(), nullable=True),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("perfil", sa.Text(), nullable=False),
        sa.Column("areas", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("senha_hash", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exp_total", sa.Integer(), nullable=False),
        sa.Column("exp_semanal", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("conquistas", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("onboarding_perfis_vistos", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("onboarding_passo", sa.Integer(), nullable=False),
        sa.Column("nivel_gestao", sa.Text(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.Text(), nullable=True),
        sa.Column("mfa_backup_codes", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("auth_provider", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_usuarios_areas", "usuarios", ["areas"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "idx_usuarios_email_lookup_hash",
        "usuarios",
        ["email_lookup_hash"],
        unique=True,
        postgresql_where=sa.text("email_lookup_hash IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_usuarios_email_lookup_hash",
        table_name="usuarios",
        postgresql_where=sa.text("email_lookup_hash IS NOT NULL"),
    )
    op.drop_index("idx_usuarios_areas", table_name="usuarios", postgresql_using="gin")
    op.drop_table("usuarios")
    # ### end Alembic commands ###
