"""chamados

Revision ID: 74f0527a9dd6
Revises: 552599f9b52c
Create Date: 2026-08-03 13:17:19.493206

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74f0527a9dd6"
down_revision: str | Sequence[str] | None = "552599f9b52c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chamados",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("numero_chamado", sa.Text(), nullable=True),
        sa.Column("categoria", sa.Text(), nullable=False),
        sa.Column("tipo_solicitacao", sa.Text(), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("responsavel", sa.Text(), nullable=True),
        sa.Column("responsavel_id", sa.Text(), nullable=True),
        sa.Column("motivo_atribuicao", sa.Text(), nullable=True),
        sa.Column("solicitante_id", sa.Text(), nullable=True),
        sa.Column("solicitante_nome", sa.Text(), nullable=True),
        sa.Column("area", sa.Text(), nullable=True),
        sa.Column("rl_codigo", sa.Text(), nullable=True),
        sa.Column("grupo_rl_id", sa.Integer(), nullable=True),
        sa.Column("gate", sa.Text(), nullable=True),
        sa.Column("impacto", sa.Text(), nullable=True),
        sa.Column("anexo", sa.Text(), nullable=True),
        sa.Column("anexos", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("setores_adicionais", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("supervisor_ids_com_acesso", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("prioridade", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "data_abertura",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_conclusao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_cancelamento", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_em_atendimento", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previsao_atendimento", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_previsao_atendimento", sa.Text(), nullable=True),
        sa.Column("motivo_cancelamento", sa.Text(), nullable=True),
        sa.Column("motivo_ultima_escalacao", sa.Text(), nullable=True),
        sa.Column("sla_dias", sa.Integer(), nullable=True),
        sa.Column("confirmacao_solicitante", sa.Text(), nullable=True),
        sa.Column("escalacao_resposta_nivel", sa.SmallInteger(), nullable=False),
        sa.Column("escalacao_resolucao_nivel", sa.SmallInteger(), nullable=False),
        sa.Column("alerta_supervisor_50_enviado", sa.Boolean(), nullable=False),
        sa.Column("alerta_supervisor_80_enviado", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grupo_rl_id"],
            ["grupos_rl.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_chamado"),
    )
    op.create_index(
        "idx_chamados_categoria_prio_data",
        "chamados",
        ["categoria", "prioridade", "data_abertura"],
        unique=False,
    )
    op.create_index(
        "idx_chamados_categoria_status_data",
        "chamados",
        ["categoria", "status", "data_abertura"],
        unique=False,
    )
    op.create_index(
        "idx_chamados_gate_status_data",
        "chamados",
        ["gate", "status", "data_abertura"],
        unique=False,
    )
    op.create_index("idx_chamados_responsavel", "chamados", ["responsavel_id"], unique=False)
    op.create_index("idx_chamados_rl_codigo", "chamados", ["rl_codigo"], unique=False)
    op.create_index(
        "idx_chamados_solicitante",
        "chamados",
        ["solicitante_id", "prioridade", "data_abertura"],
        unique=False,
    )
    op.create_index(
        "idx_chamados_status_data", "chamados", ["status", "data_abertura"], unique=False
    )
    op.create_index(
        "idx_chamados_supervisor_acesso",
        "chamados",
        ["supervisor_ids_com_acesso"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "chamados_observadores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chamado_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Text(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["chamado_id"], ["chamados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chamado_id", "usuario_id", name="uq_observador_chamado_usuario"),
    )
    op.create_table(
        "chamados_participantes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chamado_id", sa.Integer(), nullable=False),
        sa.Column("supervisor_id", sa.Text(), nullable=False),
        sa.Column("area", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["chamado_id"], ["chamados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chamado_id", "supervisor_id", name="uq_participante_chamado_supervisor"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chamados_participantes")
    op.drop_table("chamados_observadores")
    op.drop_index("idx_chamados_supervisor_acesso", table_name="chamados", postgresql_using="gin")
    op.drop_index("idx_chamados_status_data", table_name="chamados")
    op.drop_index("idx_chamados_solicitante", table_name="chamados")
    op.drop_index("idx_chamados_rl_codigo", table_name="chamados")
    op.drop_index("idx_chamados_responsavel", table_name="chamados")
    op.drop_index("idx_chamados_gate_status_data", table_name="chamados")
    op.drop_index("idx_chamados_categoria_status_data", table_name="chamados")
    op.drop_index("idx_chamados_categoria_prio_data", table_name="chamados")
    op.drop_table("chamados")
    # ### end Alembic commands ###
